###Create user 
POST http://localhost:8000/api/inventory/v1/user
Content-Type: application/json

{
  "username":"jcjimenez",
  "password":"jcjimenez",
  "store_id":1
}


###get users
GET http://localhost:8000/api/inventory/v1/user


###get user
GET http://localhost:8000/api/inventory/v1/user/1

###Login
POST http://localhost:8000/api/inventory/v1/login
Content-Type: application/json

{
  "username":"jcjimenez",
  "password":"jcjimenez"
}
